// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: proto/shop_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ShopServiceClient is the client API for ShopService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShopServiceClient interface {
	AddShop(ctx context.Context, in *NewShopData, opts ...grpc.CallOption) (*Id, error)
	FindShopById(ctx context.Context, in *Id, opts ...grpc.CallOption) (*ShopData, error)
	FindShopNearMe(ctx context.Context, in *Location, opts ...grpc.CallOption) (*MultipleShopData, error)
}

type shopServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShopServiceClient(cc grpc.ClientConnInterface) ShopServiceClient {
	return &shopServiceClient{cc}
}

func (c *shopServiceClient) AddShop(ctx context.Context, in *NewShopData, opts ...grpc.CallOption) (*Id, error) {
	out := new(Id)
	err := c.cc.Invoke(ctx, "/proto.ShopService/AddShop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) FindShopById(ctx context.Context, in *Id, opts ...grpc.CallOption) (*ShopData, error) {
	out := new(ShopData)
	err := c.cc.Invoke(ctx, "/proto.ShopService/FindShopById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) FindShopNearMe(ctx context.Context, in *Location, opts ...grpc.CallOption) (*MultipleShopData, error) {
	out := new(MultipleShopData)
	err := c.cc.Invoke(ctx, "/proto.ShopService/FindShopNearMe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShopServiceServer is the server API for ShopService service.
// All implementations must embed UnimplementedShopServiceServer
// for forward compatibility
type ShopServiceServer interface {
	AddShop(context.Context, *NewShopData) (*Id, error)
	FindShopById(context.Context, *Id) (*ShopData, error)
	FindShopNearMe(context.Context, *Location) (*MultipleShopData, error)
	mustEmbedUnimplementedShopServiceServer()
}

// UnimplementedShopServiceServer must be embedded to have forward compatible implementations.
type UnimplementedShopServiceServer struct {
}

func (UnimplementedShopServiceServer) AddShop(context.Context, *NewShopData) (*Id, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddShop not implemented")
}
func (UnimplementedShopServiceServer) FindShopById(context.Context, *Id) (*ShopData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindShopById not implemented")
}
func (UnimplementedShopServiceServer) FindShopNearMe(context.Context, *Location) (*MultipleShopData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindShopNearMe not implemented")
}
func (UnimplementedShopServiceServer) mustEmbedUnimplementedShopServiceServer() {}

// UnsafeShopServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShopServiceServer will
// result in compilation errors.
type UnsafeShopServiceServer interface {
	mustEmbedUnimplementedShopServiceServer()
}

func RegisterShopServiceServer(s grpc.ServiceRegistrar, srv ShopServiceServer) {
	s.RegisterService(&ShopService_ServiceDesc, srv)
}

func _ShopService_AddShop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewShopData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).AddShop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ShopService/AddShop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).AddShop(ctx, req.(*NewShopData))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_FindShopById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).FindShopById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ShopService/FindShopById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).FindShopById(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_FindShopNearMe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Location)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).FindShopNearMe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ShopService/FindShopNearMe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).FindShopNearMe(ctx, req.(*Location))
	}
	return interceptor(ctx, in, info, handler)
}

// ShopService_ServiceDesc is the grpc.ServiceDesc for ShopService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShopService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ShopService",
	HandlerType: (*ShopServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddShop",
			Handler:    _ShopService_AddShop_Handler,
		},
		{
			MethodName: "FindShopById",
			Handler:    _ShopService_FindShopById_Handler,
		},
		{
			MethodName: "FindShopNearMe",
			Handler:    _ShopService_FindShopNearMe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/shop_service.proto",
}
